universe = vanilla
log    =    ../log/myscript-chtc_$(Cluster)_$(Process).log
error  =  ../error/myscript-chtc_$(Cluster)_$(Process).err
output = ../output/myscript-chtc_$(Cluster)_$(Process).out

executable = ./download_unzip.sh
arguments = $(link)
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
initialdir = listings/

request_cpus = 1
request_memory = 1GB
request_disk = 500MB

queue link from file.txt